export let API_URL;
export let SOCKET_URL;

const {
    REACT_APP_PUBLIC_ENV,
    REACT_APP_PUBLIC_BASE_URL_PROD,
    REACT_APP_PUBLIC_SOCKET_SERVER_URL_PROD,
    REACT_APP_PUBLIC_BASE_URL_DEV,
    REACT_APP_PUBLIC_SOCKET_SERVER_URL_DEV
} = process.env;

if (REACT_APP_PUBLIC_ENV === 'production') {
    API_URL = REACT_APP_PUBLIC_BASE_URL_PROD;
    SOCKET_URL = REACT_APP_PUBLIC_SOCKET_SERVER_URL_PROD;
} else {
    API_URL = REACT_APP_PUBLIC_BASE_URL_DEV;
    SOCKET_URL = REACT_APP_PUBLIC_SOCKET_SERVER_URL_DEV;
}
